"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { Card, CardHeader } from "@/components/ui";
import { askAboutCompany, type AskResult } from "@/lib/ai/explain";
import { cn } from "@/lib/utils";

/**
 * Plain-English explanations of this page's own figures, written by a model.
 *
 * A handful of fixed questions, not a chat box. Every answer cites the parts
 * of the page it drew on, and says it was generated, so a reader can check it
 * against the figures rather than take it on trust.
 */
export function AskAboutFigures({
  symbol,
  companyName,
  signedIn,
  questions,
}: {
  symbol: string;
  companyName: string;
  signedIn: boolean;
  questions: { key: string; label: string }[];
}) {
  const [asked, setAsked] = useState<string | null>(null);
  const [result, setResult] = useState<AskResult | null>(null);
  const [pending, startTransition] = useTransition();

  function ask(key: string) {
    setAsked(key);
    setResult(null);
    startTransition(async () => {
      setResult(await askAboutCompany(symbol, key));
    });
  }

  return (
    <Card>
      <CardHeader
        title="Ask about these figures"
        subtitle={`Explanations of ${companyName}'s figures, written by an AI model from this page only, with each statement cited`}
      />
      <div className="space-y-4 p-5">
        {signedIn ? (
          <div className="flex flex-wrap gap-2" role="group" aria-label="Questions">
            {questions.map((question) => (
              <button
                key={question.key}
                type="button"
                onClick={() => ask(question.key)}
                disabled={pending}
                aria-pressed={asked === question.key}
                className={cn(
                  "rounded-lg border px-3 py-1.5 text-sm font-medium transition-colors disabled:opacity-60",
                  asked === question.key
                    ? "border-accent bg-accent-soft text-accent"
                    : "border-border text-muted-strong hover:border-accent hover:text-accent",
                )}
              >
                {question.label}
              </button>
            ))}
          </div>
        ) : (
          <p className="text-sm text-muted">
            <Link
              href={`/signin?next=${encodeURIComponent(`/stock/${symbol}`)}`}
              className="text-accent underline underline-offset-2"
            >
              Sign in
            </Link>{" "}
            to ask for a plain-English explanation of these figures.
          </p>
        )}

        {pending && (
          <p role="status" className="text-sm text-muted">
            Reading the figures…
          </p>
        )}

        {result && !result.ok && (
          <p role="alert" className="text-sm text-poor">
            {result.message}
          </p>
        )}

        {result?.ok && result.answer && (
          <div className="space-y-3" aria-live="polite">
            <div className="space-y-2 text-[0.9375rem] leading-relaxed text-muted-strong">
              {result.answer.split(/\n{2,}/).map((paragraph, index) => (
                <p key={index}>{paragraph}</p>
              ))}
            </div>
            {result.sources && result.sources.length > 0 && (
              <div>
                <h3 className="text-xs font-medium text-muted">Sources cited</h3>
                <ul className="mt-1 space-y-0.5 text-xs">
                  {result.sources.map((source) => (
                    <li key={source.id}>
                      <span className="tnum text-faint">[{source.id}]</span>{" "}
                      {source.url ? (
                        source.url.startsWith("/") ? (
                          <a href={source.url.replace(/^\/stock\/[^#]+/, "")} className="text-accent hover:underline">
                            {source.label}
                          </a>
                        ) : (
                          <a href={source.url} target="_blank" rel="noreferrer noopener" className="text-accent hover:underline">
                            {source.label}
                          </a>
                        )
                      ) : (
                        source.label
                      )}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            <p className="text-xs leading-relaxed text-faint">
              Generated by {result.model} from the figures on this page. It can be wrong, so check
              each cited source. Educational information only — not investment advice.
            </p>
          </div>
        )}
      </div>
    </Card>
  );
}
